# Test against this version of Node.js
environment:
  nodejs_version: "6"
  access_token:
    secure: wShbQfYcfaf2ZgU8dFgLTVJglCyGiK9/BHWcEbVZ4sU8SqxokPc4pFfl1ZY4qtlO


# only build master (currently this is the only way to avoid the build failing on other branches)
branches:
  only:
    - master

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm config set loglevel warn
  - npm install --silent

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - cmd: test.bat

build_script:
  - cmd: update.bat

before_build:
 - git checkout master

on_success:
 - git config --global credential.helper store
 - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
 - git config --global user.email "bbbbbbenes@outlook.com.br"
 - git config --global user.name "Appveyor Automated Build"
 - cmd: For /f "tokens=2-4 delims=/ " %%a in ('date /t') do (set mydate=%%c-%%a-%%b)
 - cmd: For /f "tokens=1-2 delims=/:" %%a in ('time /t') do (set mytime=%%a%%b)
 - cmd: addall.bat md
 - git commit -m "Built markdown at %mydate%_%mytime% [skip ci]"
 - git push origin master
